DROP TABLE IF EXISTS "ACCIDENT_TYPE" CASCADE;
DROP TABLE IF EXISTS "ACCIDENT_LIGHT_CONDITION" CASCADE;
DROP TABLE IF EXISTS "ROAD" CASCADE;
DROP TABLE IF EXISTS "ROAD_SPEED" CASCADE;
DROP TABLE IF EXISTS "STATE_DIV" CASCADE;
DROP TABLE IF EXISTS "DEGREE_URBAN" CASCADE;
DROP TABLE IF EXISTS "REGION" CASCADE;
DROP TABLE IF EXISTS "LGA" CASCADE;
DROP TABLE IF EXISTS "ACCIDENT_SEVERITY" CASCADE;
DROP TABLE IF EXISTS "ACCIDENT" CASCADE;
DROP TABLE IF EXISTS "ACCIDENT_PERSON_INVOLVED_COUNT" CASCADE;
DROP TABLE IF EXISTS "ACCIDENT_VEHICLE_INVOLVED_COUNT" CASCADE;


CREATE TABLE "ACCIDENT_TYPE" (
	"ACCIDENT_TYPE_ID" INT NOT NULL,
	"ACCIDENT_TYPE_DESCRIPTION" VARCHAR NOT NULL,
	CONSTRAINT "PK_ACCIDENT_TYPE" PRIMARY KEY (
		"ACCIDENT_TYPE_ID"
	)
);

CREATE TABLE "ACCIDENT_LIGHT_CONDITION" (
	"ACCIDENT_LIGHT_CONDITION_ID" INT NOT NULL,
	"ACCIDENT_LIGHT_CONDITION_DESCRIPTION" VARCHAR NOT NULL,
	CONSTRAINT "PK_ACCIDENT_LIGHT_CONDITION" PRIMARY KEY (
		"ACCIDENT_LIGHT_CONDITION_ID"
	)
);

CREATE TABLE "ROAD" (
	"ROAD_ID" INT NOT NULL,
	"ROAD_GEOMETRY" VARCHAR NOT NULL,
	CONSTRAINT "PK_ROAD" PRIMARY KEY (
		"ROAD_ID"
	)
);

CREATE TABLE "ROAD_SPEED" (
	"ROAD_SPEED_ZONE" VARCHAR NOT NULL,
	CONSTRAINT "PK_ROAD_SPEED" PRIMARY KEY (
		"ROAD_SPEED_ZONE"
	)
);

CREATE TABLE "STATE_DIV" (
	"STATE_DIV_ID" INT NOT NULL,
	"STATE_DIV_NAME" VARCHAR NOT NULL,
	CONSTRAINT "PK_STATE_DIV" PRIMARY KEY (
		"STATE_DIV_ID"
	)
);

CREATE TABLE "DEGREE_URBAN" (
	"DEGREE_URBAN_ID" INT NOT NULL,
	"DEGREE_URBAN_DESCRIPTION" VARCHAR NOT NULL,
	"STATE_DIV_ID" INT NOT NULL,
	CONSTRAINT "PK_DEGREE_URBAN" PRIMARY KEY (
		"DEGREE_URBAN_ID"
	)
);

CREATE TABLE "REGION" (
	"REGION_ID" INT NOT NULL,
	"REGION_NAME" VARCHAR NOT NULL,
	"DEGREE_URBAN_ID" INT NOT NULL,
	CONSTRAINT "PK_REGION" PRIMARY KEY (
		"REGION_ID"
	)
);

CREATE TABLE "LGA" (
	"LGA_ID" INT NOT NULL,
	"LGA_NAME" VARCHAR NOT NULL,
	"REGION_ID" INT NOT NULL,
	CONSTRAINT "PK_LGA" PRIMARY KEY (
		"LGA_ID"
	)
);

CREATE TABLE "ACCIDENT_SEVERITY" (
	"ACCIDENT_SEVERITY_ID" INT NOT NULL,
	"ACCIDENT_SEVERITY_DESCRIPTION" VARCHAR NOT NULL,
	CONSTRAINT "PK_ACCIDENT_SEVERITY_DESCRIPTION" PRIMARY KEY (
		"ACCIDENT_SEVERITY_ID"
	)
);

CREATE TABLE "ACCIDENT" (
	"ACCIDENT_NO" VARCHAR NOT NULL,
	"ACCIDENT_DATETIME" DATE NOT NULL,
	"ACCIDENT_TYPE_ID" INT NOT NULL,
	"ACCIDENT_ALCHOL_TIME" BOOLEAN NOT NULL,
	"ACCIDENT_DAY_OF_WEEK" VARCHAR NOT NULL,
	"ACCIDENT_DCA_CODE" VARCHAR NOT NULL,
	"ACCIDENT_LIGHT_CONDITION_ID" INT NOT NULL,
	"ACCIDENT_HIT_RUN_FLAG" BOOLEAN NOT NULL,
	"ACCIDENT_RUN_OFFROAD" BOOLEAN NOT NULL,
	"ACCIDENT_SEVERITY_ID" INT NOT NULL,
	"ACCIDENT_LATITUDE" DECIMAL NOT NULL,
	"ACCIDENT_LONGTITUDE" DECIMAL NOT NULL,
	"ACCIDENT_TOTAL_PEOPLE_INVOLVED_COUNT" INT NOT NULL,
	"ACCIDENT_TOTAL_VEHICLE_INVOLVED_COUNT" INT NOT NULL,
	"ACCIDENT_ALCOHOL_RELATED" BOOLEAN NOT NULL,
	"ACCIDENT_WITHOUT_LICENSE" BOOLEAN NOT NULL,
	"ROAD_ID" INT NOT NULL,
	"LGA_ID" INT NOT NULL,
	"ROAD_SPEED_ZONE" VARCHAR NOT NULL,
	
	CONSTRAINT "PK_ACCIDENT" PRIMARY KEY (
		"ACCIDENT_NO"
	)
);

CREATE TABLE "ACCIDENT_PERSON_INVOLVED_COUNT" (
	"ACCIDENT_NO" VARCHAR NOT NULL,
	"ACCIDENT_FATALITY_COUNT" INT,
	"ACCIDENT_SERIOUS_INJURY_COUNT" INT,
	"ACCIDENT_OTHER_INJURY_COUNT" INT,
	"ACCIDENT_NON_INJURY_COUNT" INT,
	"ACCIDENT_MALE_COUNT" INT,
	"ACCIDENT_FEMALE_COUNT" INT,
	"ACCIDENT_BICYCLIST_COUNT" INT,
	"ACCIDENT_PASSENGER_COUNT" INT,
	"ACCIDENT_DRIVER_COUNT" INT,
	"ACCIDENT_PEDESTRIAN_COUNT" INT,
	"ACCIDENT_PILLION_COUNT" INT,
	"ACCIDENT_MOTORIST_COUNT" INT,
	"ACCIDENT_PED_CYCLIST_5TO12_COUNT" INT,
	"ACCIDENT_PED_CYCLIST_13TO18_COUNT" INT,
	"ACCIDENT_OLD_PEDESTRIAN_COUNT" INT,
	"ACCIDENT_OLD_DRIVER_COUNT" INT,
	"ACCIDENT_YOUNG_DRIVER_COUNT" INT,
	CONSTRAINT "PK_ACCIDENT_PERSON_COUNT" PRIMARY KEY (
		"ACCIDENT_NO"
	)
);

CREATE TABLE "ACCIDENT_VEHICLE_INVOLVED_COUNT" (
	"ACCIDENT_NO" VARCHAR NOT NULL,
	"ACCIDENT_HEAVY_VEHICLE_COUNT" INT,
	"ACCIDENT_PASSENGER_VEHICLE_COUNT" INT,
	"ACCIDENT_MOTORCYCLE_COUNT" INT,
	"ACCIDENT_PUBLIC_VEHICLE_COUNT" INT,
	CONSTRAINT "PK_ACCIDENT_VEHICLE_COUNT" PRIMARY KEY (
		"ACCIDENT_NO"
	)
);


ALTER TABLE "DEGREE_URBAN" ADD CONSTRAINT "FK_STATE_DIV_ID" FOREIGN KEY("STATE_DIV_ID")
REFERENCES "STATE_DIV" ("STATE_DIV_ID");

ALTER TABLE "REGION" ADD CONSTRAINT "FK_DEGREE_URBAN_ID" FOREIGN KEY("DEGREE_URBAN_ID")
REFERENCES "DEGREE_URBAN" ("DEGREE_URBAN_ID");

ALTER TABLE "LGA" ADD CONSTRAINT "FK_REGION_ID" FOREIGN KEY("REGION_ID")
REFERENCES "REGION" ("REGION_ID");

ALTER TABLE "ACCIDENT" ADD CONSTRAINT "FK_ACCIDENT_TYPE_ID" FOREIGN KEY("ACCIDENT_TYPE_ID")
REFERENCES "ACCIDENT_TYPE" ("ACCIDENT_TYPE_ID");

ALTER TABLE "ACCIDENT" ADD CONSTRAINT "FK_ACCIDENT_LIGHT_CONDITION_ID" FOREIGN KEY("ACCIDENT_LIGHT_CONDITION_ID")
REFERENCES "ACCIDENT_LIGHT_CONDITION" ("ACCIDENT_LIGHT_CONDITION_ID");

ALTER TABLE "ACCIDENT" ADD CONSTRAINT "FK_ACCIDENT_SEVERITY_ID_ASFK" FOREIGN KEY("ACCIDENT_SEVERITY_ID")
REFERENCES "ACCIDENT_SEVERITY" ("ACCIDENT_SEVERITY_ID");

ALTER TABLE "ACCIDENT" ADD CONSTRAINT "FK_ROAD_ID" FOREIGN KEY("ROAD_ID")
REFERENCES "ROAD" ("ROAD_ID");

ALTER TABLE "ACCIDENT" ADD CONSTRAINT "FK_LGA_ID" FOREIGN KEY("LGA_ID")
REFERENCES "LGA" ("LGA_ID");

ALTER TABLE "ACCIDENT" ADD CONSTRAINT "FK_ROAD_SPEED_ZONE" FOREIGN KEY("ROAD_SPEED_ZONE")
REFERENCES "ROAD_SPEED" ("ROAD_SPEED_ZONE");

ALTER TABLE "ACCIDENT_PERSON_INVOLVED_COUNT" ADD CONSTRAINT "FK_ACCIDENT_NO_PERSON_COUNT" FOREIGN KEY("ACCIDENT_NO")
REFERENCES "ACCIDENT" ("ACCIDENT_NO");

ALTER TABLE "ACCIDENT_VEHICLE_INVOLVED_COUNT" ADD CONSTRAINT "FK_ACCIDENT_NO_VEHICLE_COUNT" FOREIGN KEY("ACCIDENT_NO")
REFERENCES "ACCIDENT" ("ACCIDENT_NO");

